# Generated by Django 3.2.4 on 2021-12-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unreadMessages',
            field=models.IntegerField(default=1),
        ),
    ]
